app:
  server:
    id: 1

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/local_tsm
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

### thymeleaf
  thymeleaf:
    cache: false
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: utf-8
    excluded-view-names:
    prefix: classpath:/templates/
    suffix: .html

###  freemarker
#  freemarker:
#    cache: false
#    suffix: .html
#    charset: UTF-8
#    template-loader-path: classpath:/templates/

#### jsp
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp


#  profiles:
#    include: freemarker

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.xiaozhi.model
