# 启用缓存:建议生产开启
# 建议模版是否存在
spring:
  thymeleaf:
    cache: false
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: utf-8
    excluded-view-names:
    prefix: classpath:/templates/
    suffix: .html