# 启用缓存:建议生产开启
# 建议模版是否存在
spring:
  freemarker:
    cache: false
    check-template-location: true
    content-type: text/html
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    charset: UTF-8
    template-loader-path: classpath:/templates/